
import { AppContextType } from './AppContextTypes';

export const defaultContextValues: AppContextType = {
  // Default empty values for data arrays
  customers: [],
  products: [],
  orders: [],
  payments: [],
  routes: [],
  loads: [],
  salesReps: [],
  vehicles: [],
  paymentMethods: [],
  paymentTables: [],
  productGroups: [],
  productCategories: [],
  productBrands: [],
  deliveryRoutes: [],
  backups: [],
  
  // Default loading states
  isLoadingCustomers: true,
  isLoadingProducts: true,
  isLoadingOrders: true,
  isLoadingPayments: true,
  isLoadingRoutes: true,
  isLoadingLoads: true,
  isLoadingSalesReps: true,
  isLoadingVehicles: true,
  isLoadingPaymentMethods: true,
  isLoadingPaymentTables: true,
  isLoadingProductGroups: true,
  isLoadingProductCategories: true,
  isLoadingProductBrands: true,
  isLoadingDeliveryRoutes: true,
  isLoadingBackups: true,
  
  // Empty setters
  setCustomers: () => {},
  setProducts: () => {},
  setOrders: () => {},
  setPayments: () => {},
  setRoutes: () => {},
  setLoads: () => {},
  setSalesReps: () => {},
  setVehicles: () => {},
  setPaymentMethods: () => {},
  setPaymentTables: () => {},
  setProductGroups: () => {},
  setProductCategories: () => {},
  setProductBrands: () => {},
  setDeliveryRoutes: () => {},
  setBackups: () => {},
  
  // Empty method implementations
  addRoute: async () => "",
  updateRoute: async () => {},
  deleteRoute: async () => {},
  addCustomer: async () => "",
  updateCustomer: async () => {},
  deleteCustomer: async () => {},
  generateNextCustomerCode: () => 1,
  addProduct: async () => "",
  updateProduct: async () => {},
  deleteProduct: async () => {},
  validateProductDiscount: () => true,
  getMinimumPrice: () => 0,
  getOrderById: () => undefined,
  addOrder: async () => "",
  updateOrder: async () => "",
  deleteOrder: async () => {},
  addVehicle: async () => "",
  updateVehicle: async () => {},
  deleteVehicle: async () => {},
  addPayment: async () => "",
  updatePayment: async () => {},
  deletePayment: async () => {},
  addPaymentMethod: async () => "",
  updatePaymentMethod: async () => {},
  deletePaymentMethod: async () => {},
  addLoad: async () => "",
  updateLoad: async () => {},
  deleteLoad: async () => {},
  addSalesRep: async () => "",
  updateSalesRep: async () => {},
  deleteSalesRep: async () => {},
  addPaymentTable: async () => "",
  updatePaymentTable: async () => {},
  deletePaymentTable: async () => {},
  addProductGroup: async () => "",
  updateProductGroup: async () => {},
  deleteProductGroup: async () => {},
  addProductCategory: async () => "",
  updateProductCategory: async () => {},
  deleteProductCategory: async () => {},
  addProductBrand: async () => "",
  updateProductBrand: async () => {},
  deleteProductBrand: async () => {},
  addDeliveryRoute: async () => "",
  updateDeliveryRoute: async () => {},
  deleteDeliveryRoute: async () => {},
  createBackup: () => "",
  restoreBackup: () => false,
  deleteBackup: () => false,
  settings: null,
  updateSettings: async () => false,
  startNewMonth: () => {},
  createAutomaticPaymentRecord: async () => {},
  clearCache: async () => {}, // Add the missing clearCache property
};
