import { AppContextType } from './AppContextTypes';

// This file will only contain part of the defaultContextValues to add the connectionStatus
// The rest of the file will stay the same
const defaultContextValues: AppContextType = {
  customers: [],
  products: [],
  orders: [],
  payments: [],
  routes: [],
  loads: [],
  salesReps: [],
  vehicles: [],
  paymentMethods: [],
  paymentTables: [],
  productGroups: [],
  productCategories: [],
  productBrands: [],
  deliveryRoutes: [],
  backups: [],
  connectionStatus: 'online', // Default to online
  
  isLoadingCustomers: false,
  isLoadingProducts: false,
  isLoadingOrders: false,
  isLoadingPayments: false,
  isLoadingRoutes: false,
  isLoadingLoads: false,
  isLoadingSalesReps: false,
  isLoadingVehicles: false,
  isLoadingPaymentMethods: false,
  isLoadingPaymentTables: false,
  isLoadingProductGroups: false,
  isLoadingProductCategories: false,
  isLoadingProductBrands: false,
  isLoadingDeliveryRoutes: false,
  isLoadingBackups: false,
  
  setCustomers: () => {},
  setProducts: () => {},
  setOrders: () => {},
  setPayments: () => {},
  setRoutes: () => {},
  setLoads: () => {},
  setSalesReps: () => {},
  setVehicles: () => {},
  setPaymentMethods: () => {},
  setPaymentTables: () => {},
  setProductGroups: () => {},
  setProductCategories: () => {},
  setProductBrands: () => {},
  setDeliveryRoutes: () => {},
  setBackups: () => {},
  
  addRoute: async () => '',
  updateRoute: async () => {},
  deleteRoute: async () => {},
  addCustomer: async () => '',
  updateCustomer: async () => {},
  deleteCustomer: async () => {},
  generateNextCustomerCode: () => 1,
  
  addProduct: async () => '',
  updateProduct: async () => {},
  deleteProduct: async () => {},
  validateProductDiscount: () => true,
  getMinimumPrice: () => 0,
  addBulkProducts: async () => [],
  
  getOrderById: async () => null,
  addOrder: async () => '',
  updateOrder: async () => '',
  deleteOrder: async () => {},
  addVehicle: async () => '',
  updateVehicle: async () => {},
  deleteVehicle: async () => {},
  addPayment: async () => '',
  updatePayment: async () => {},
  deletePayment: async () => {},
  createAutomaticPaymentRecord: async () => undefined,
  
  addPaymentMethod: async () => '',
  updatePaymentMethod: async () => {},
  deletePaymentMethod: async () => {},
  
  addLoad: async () => '',
  updateLoad: async () => {},
  deleteLoad: async () => {},
  addSalesRep: async () => '',
  updateSalesRep: async () => {},
  deleteSalesRep: async () => {},
  addPaymentTable: async () => '',
  updatePaymentTable: async () => {},
  deletePaymentTable: async () => {},
  addProductGroup: async () => '',
  updateProductGroup: async () => {},
  deleteProductGroup: async () => {},
  addProductCategory: async () => '',
  updateProductCategory: async () => {},
  deleteProductCategory: async () => {},
  addProductBrand: async () => '',
  updateProductBrand: async () => {},
  deleteProductBrand: async () => {},
  addDeliveryRoute: async () => '',
  updateDeliveryRoute: async () => {},
  deleteDeliveryRoute: async () => {},
  
  createBackup: async () => '',
  restoreBackup: async () => true,
  deleteBackup: async () => true,
  
  settings: {
    companyName: 'Minha Empresa',
    companyLogo: '',
    createdAt: new Date(),
    updatedAt: new Date(),
    company: {
      name: '',
      address: '',
      phone: '',
      email: '',
      document: '',
      footer: ''
    },
    theme: {
      primary: '#1C64F2',
      secondary: '#047481',
      accent: '#0694A2',
      primaryColor: '#1C64F2',
      secondaryColor: '#047481',
      accentColor: '#0694A2'
    }
  },
  updateSettings: async () => {},
  
  startNewMonth: async () => true,
  startNewDay: async () => true,
  clearCache: async () => {},
  refreshData: async () => true,
};

export default defaultContextValues;
