import { AppContextType, AppSettings } from './AppContextTypes';

// Default values for the context
const defaultContextValues: Omit<AppContextType, 'setAppSettings' | 'appSettings' | 'setProducts' | 'setCategories' | 'setBrands' | 'setSalesReps'> = {
  isOnline: true,
  toggleSidebar: () => {},
  sidebarOpen: false,
  products: [],
  categories: [],
  brands: [],
  salesReps: [],
  customers: [],
  orders: [],
  payments: [],
  loadOrders: [],
  addProduct: async () => "",
  updateProduct: async () => {},
  deleteProduct: async () => {},
  addProductCategory: async () => "",
  updateProductCategory: async () => {},
  deleteProductCategory: async (): Promise<boolean> => Promise.resolve(false),
  addProductBrand: async () => "",
  updateProductBrand: async () => {},
  deleteProductBrand: async (): Promise<boolean> => Promise.resolve(false),
  addCustomer: async () => "",
  updateCustomer: async () => {},
  deleteCustomer: async () => {},
  addSalesRep: async () => "",
  updateSalesRep: async () => {},
  deleteSalesRep: async () => {},
  addOrder: async () => "",
  updateOrder: async () => {},
  deleteOrder: async () => {},
  addPayment: async () => "",
  updatePayment: async () => {},
  deletePayment: async () => {},
  addLoadOrder: async () => "",
  updateLoadOrder: async () => {},
  deleteLoadOrder: async () => {},
  generateNextProductCode: () => 1,
  generateNextCustomerCode: () => 1,
  generateNextOrderCode: () => 1,
  generateNextPaymentCode: () => 1,
  generateNextLoadOrderCode: () => 1,
  refreshProducts: async () => {},
  refreshCustomers: async () => {},
  refreshSalesReps: async () => {},
  refreshOrders: async () => {},
  refreshPayments: async () => {},
  refreshLoadOrders: async () => {},
  isLoadingProducts: false,
  isLoadingCustomers: false,
  isLoadingSalesReps: false,
  isLoadingOrders: false,
  isLoadingPayments: false,
  isLoadingLoadOrders: false,
};

export const defaultSettings: AppSettings = {
  // Make sure these field names match the AppSettings interface
  company_name: '',
  company_address: '',
  company_phone: '',
  company_email: '',
  company_document: '',
  company_footer: '',
  primary_color: '#1C64F2',
  secondary_color: '#047481',
  accent_color: '#0694A2'
};

export default defaultContextValues;
