// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etrkhbbklcmnjuypfllf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0cmtoYmJrbGNtbmp1eXBmbGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTU2MzgsImV4cCI6MjA2MjMzMTYzOH0.xH9BnB1WzMfJrXZLotqT5lZ-OABdjygmOmK-BtHx56Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);